project_type: node
slug: nocturnaagency
port: 3000

domains:
  prod: nocturnaagency.co.uk
  admin: admin.nocturnaagency.co.uk

deploy_targets:
  main-hetz: hetzner
  dev: vercel
  preview: vercel

pgadmin_subdomain: dbui
pgadmin_subdomain: db
